export const projects = [
  {
    title: "CashaBlanca (Financial Dashboard)",
    demo: "",
    link: "https://github.com/Moriarty777/CashaBlanca",
    col: 5,
    row: 3,
    variant: "sub",
  },
  {
    title: "Le Cigare Volant",
    demo: "https://le-cigare-volant.vercel.app/",
    link: "https://github.com/Moriarty777/le-cigare-volant",
    col: 4,
    row: 3,
    variant: "sub",
  },
  {
    title: "Fetch Receipt API",
    demo: "",
    link: "https://github.com/Moriarty777/fetch-receipt-api",
    col: 3,
    row: 6,
    variant: "sub",
  },
  {
    title: "Projects",
    degree: "Check out the projects I’ve built and contributed to.",
    gradientFrom: "#F4A261",
    gradientTo: "#FFE8D6",
    col: 3,
    row: 3,
    buttonText: "Go Back",
    path: "/",
    variant: "main",
  },
  {
    title: "Bento Folio",
    demo: "https://bento-folio-jade.vercel.app/",
    link: "https://github.com/Moriarty777/bento_folio",
    col: 3,
    row: 6,
    variant: "sub",
  },
  {
    title: "More to Come ...",
    demo: "",
    link: "",
    col: 3,
    row: 3,
    variant: "sub",
  },
];
