export const technology = [
  {
    title: "Javascript",
    icon: "https://cdn.simpleicons.org/javascript",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "React",
    icon: "https://cdn.simpleicons.org/react",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Typescript",
    icon: "https://cdn.simpleicons.org/typescript",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "HTML",
    icon: "https://cdn.simpleicons.org/html5",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "CSS",
    icon: "https://cdn.simpleicons.org/css",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Tailwind",
    icon: "https://cdn.simpleicons.org/tailwindcss",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Next.js",
    icon: "https://cdn.simpleicons.org/nextdotjs",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Technology",
    description: "Explore the tools and frameworks I work with.",
    gradientFrom: "#FFB400",
    gradientTo: "#fde8b7",
    row: 4,
    col: 2,
    buttonText: "Go Back",
    path: "/",
    hover: false,
    variant: "main",
  },
  {
    title: "Redux",
    icon: "https://cdn.simpleicons.org/redux",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Jest",
    icon: "https://cdn.simpleicons.org/jest",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Node.js",
    icon: "https://cdn.simpleicons.org/nodedotjs",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Express.js",
    icon: "https://cdn.simpleicons.org/express",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Python",
    icon: "https://cdn.simpleicons.org/python",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "PostgreSQL",
    icon: "https://cdn.simpleicons.org/postgresql",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Docker",
    icon: "https://cdn.simpleicons.org/docker",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Git",
    icon: "https://cdn.simpleicons.org/git",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Figma",
    icon: "https://cdn.simpleicons.org/figma",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "Ubuntu",
    icon: "https://cdn.simpleicons.org/ubuntu",
    row: 2,
    col: 2,
    variant: "sub",
  },
  {
    title: "D3.js",
    icon: "https://cdn.simpleicons.org/d3",
    row: 2,
    col: 2,
    variant: "sub",
  },
];
