export const workExperience = [
  {
    company: "ParishOnNet",
    location: "Chicago, IL",
    role: "Software Engineer",
    description:
      "Collaborated with cross-functional teams to develop scalable web applications using React, TypeScript, and Tailwind CSS, integrating APIs, ensuring code quality, and implementing testing in a fast-paced environment.",
    textColor: "text-gray-100",
    icon: "/images/logo/parishonnet.png",
    col: 5,
    row: 3,
    variant: "sub",
  },
  {
    company: "Jaia Robotics",
    location: "Bristol, RI",
    role: "Software Developer Intern",
    description:
      "Designed user dashboards, integrated REST APIs, and enhanced UI/UX for efficient and responsive interfaces.",
    textColor: "text-gray-100",
    icon: "/images/logo/jaia.png",
    col: 4,
    row: 3,
    variant: "sub",
  },
  {
    company: "Indian Institute of Technology Bombay",
    location: "Mumbai",
    role: "Sr. Project Technical Assistant",
    description:
      "Enhanced UI functionality, improved code quality, and optimized simulator usability by 25%.",
    textColor: "text-gray-100",
    icon: "/images/logo/iitb.png",
    col: 3,
    row: 6,
    variant: "sub",
  },
  {
    company: "Work Experience",
    description: "Explore my journey in the tech industry.",
    gradientFrom: "#3C91E6",
    gradientTo: "#c6e7db",
    col: 3,
    row: 3,
    buttonText: "Go Back",
    path: "/",
    hover: false,
    variant: "main",
  },
  {
    company: "Indian Institute of Technology Bombay",
    location: "Mumbai",
    role: "Project Research Assistant",
    description:
      "Developed a Scilab Converter prototype using Python to migrate block diagram models and implement new regulations.",
    textColor: "text-gray-100",
    icon: "/images/logo/iitb.png",
    col: 3,
    row: 6,
    variant: "sub",
  },
  {
    company: "More to Come ...",
    textColor: "text-gray-100",
    col: 3,
    row: 3,
    variant: "sub",
  },
];
